"""Initial docdiff schema

Revision ID: 671d728b59d1
Revises: 
Create Date: 2026-04-17 12:20:37.160387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '671d728b59d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='docdiff'
    )
    op.create_table('comparison_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'parsing_version_a', 'parsing_version_b', 'aligning', 'diffing', 'classifying', 'assembling', 'ready_for_review', 'verification_in_progress', 'completed', 'failed', 'cancelled', name='jobstatus', schema='docdiff'), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('stage_progress', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_differences', sa.Integer(), nullable=False),
    sa.Column('differences_verified', sa.Integer(), nullable=False),
    sa.Column('auto_confirm_threshold', sa.Float(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('company_id', sa.String(length=255), nullable=True),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='docdiff'
    )
    op.create_table('detected_differences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('difference_number', sa.Integer(), nullable=False),
    sa.Column('difference_type', sa.Enum('text_addition', 'text_deletion', 'text_modification', 'table_cell_change', 'table_row_addition', 'table_row_deletion', 'table_structure_change', 'annotation_present_in_b', 'annotation_removed_from_b', 'section_moved', 'formatting_change', name='differencetype', schema='docdiff'), nullable=False),
    sa.Column('significance', sa.Enum('material', 'substantive', 'cosmetic', 'uncertain', name='significance', schema='docdiff'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('page_version_a', sa.Integer(), nullable=True),
    sa.Column('page_version_b', sa.Integer(), nullable=True),
    sa.Column('bbox_version_a', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('bbox_version_b', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('value_before', sa.Text(), nullable=True),
    sa.Column('value_after', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('block_id_version_a', sa.String(length=100), nullable=True),
    sa.Column('block_id_version_b', sa.String(length=100), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'confirmed', 'dismissed', 'corrected', 'flagged', name='verificationstatus', schema='docdiff'), nullable=False),
    sa.Column('auto_confirmed', sa.Boolean(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('verifier_comment', sa.Text(), nullable=True),
    sa.Column('corrected_description', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['docdiff.comparison_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='docdiff'
    )
    op.create_table('diff_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('summary_stats', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('report_pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['docdiff.comparison_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id'),
    sa.UniqueConstraint('job_id', name='uq_diff_reports_job_id'),
    schema='docdiff'
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('version_a', 'version_b', name='documentrole', schema='docdiff'), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('pdf_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['docdiff.comparison_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='docdiff'
    )
    op.create_table('document_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.Enum('born_digital', 'scanned', 'mixed', name='pagetype', schema='docdiff'), nullable=False),
    sa.Column('has_handwriting', sa.Boolean(), nullable=False),
    sa.Column('has_annotations', sa.Boolean(), nullable=False),
    sa.Column('content', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=1000), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'completed', 'failed', name='pageprocessingstatus', schema='docdiff'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['docdiff.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='docdiff'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_pages', schema='docdiff')
    op.drop_table('documents', schema='docdiff')
    op.drop_table('diff_reports', schema='docdiff')
    op.drop_table('detected_differences', schema='docdiff')
    op.drop_table('comparison_jobs', schema='docdiff')
    op.drop_table('api_keys', schema='docdiff')
    # ### end Alembic commands ###
