"""add reviewer_corrections table

Revision ID: c798bf45b3e9
Revises: 671d728b59d1
Create Date: 2026-04-18 00:11:26.254182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c798bf45b3e9'
down_revision: Union[str, None] = '671d728b59d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value_before', sa.Text(), nullable=False),
    sa.Column('value_after', sa.Text(), nullable=False),
    sa.Column('difference_type', sa.String(length=100), nullable=False),
    sa.Column('original_significance', sa.String(length=50), nullable=False),
    sa.Column('corrected_significance', sa.String(length=50), nullable=False),
    sa.Column('verifier_comment', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='docdiff'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewer_corrections', schema='docdiff')
    # ### end Alembic commands ###
